version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  test:
    docker:
      - image: 'circleci/node:15.12-browsers-legacy'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn run test
  deploy:
    docker:
      - image: 'circleci/node:15.12'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn run deploy     
workflows:
  test:
    jobs:
      - test
  deploy:
    jobs:
      - deploy
      filters:
        branches:
          only:
            - master
